### ISSUE TITLE
关于小明bot中比赛提醒插件的修改

### ISSUE THREAD

**Issue by Lanly109** [bobby285271/bobby285271#1]
您好，我曾经在牛客交流群里看见过小明bot，并见过它强大的查找cf用户信息以及比赛提醒的功能。
无意间我在您仓库里发现了这个插件的[源码](https://github.com/bobby285271/xiaoming-bot)，基于nonebot写的。
我想把它移植到[Hoshinobot](https://github.com/Ice-Cirno/HoshinoBot)，并优化下代码逻辑，放入我的bot中。
同时也有可能会将bot拉到其他群里使用该插件。
由于[该仓库](https://github.com/bobby285271/xiaoming-bot)没有任何License，以及[小明机器人的 QQ 空间](https://user.qzone.qq.com/3530632181)设置了权限我无法访问，根据您的[github简介](https://github.com/bobby285271)才在此提出issue想征求您的同意，如有打扰还请谅解，谢谢！

**Comment by bobby285271** [comment]
啊啊啊啊不好意思我不是这个项目的作者，也确实不知道作者的意愿如何，无法给出确定的答复，真的非常抱歉！

**Comment by Lanly109** [comment]
> 啊啊啊啊不好意思我不是这个项目的作者，也确实不知道作者的意愿如何，无法给出确定的答复，真的非常抱歉！

啊啊没事qwq那那打扰了，感谢您。
